feat: added config to poyfill node js modules
verida/react-stater-kit pull request #6
Opened 2022-09-15 05:23 UTC by cmcWebCode40

- Added config to support nodejs modules that are not supported in webpack 5

for context see the thread 
https://discord.com/channels/664594912460668960/929954765021011978/1018852026932801586

2022-09-23 01:02 UTC, aurelticot requested changes
Just a few questions.
Otherwise ok

2022-09-23 01:02 UTC, aurelticot commented on config-overrides.js
> +            Buffer: [require.resolve("buffer/"), "Buffer"]
Also, I've seen and used other configs where it was just `Buffer: ["buffer", "Buffer"],`.
Is it ok with the `require.resolve("...")` part?

2022-09-26 12:59 UTC, cmcWebCode40 commented on config-overrides.js
> +            Buffer: [require.resolve("buffer/"), "Buffer"]
yes its actually important and its specified here https://www.npmjs.com/package/buffer#usage

> Is it ok with the require.resolve("...") part?
Yes it is works as expected

2022-10-20 03:54 UTC, aurelticot requested changes

2022-10-20 03:54 UTC, aurelticot commented on package.json
> +    "react-loader-spinner": "^5.3.4",
As we removed the import in `src/index.js`, do we actually use this dependency somewhere?
If not, we should remove it completely

2022-10-20 12:45 UTC, cmcWebCode40 commented on package.json
> +    "react-loader-spinner": "^5.3.4",
@aurelticot,

The dependency was used in this view component here 

https://github.com/verida/react-stater-kit/blob/7ccad096974a6f31650baea21216561d52d356f7/src/pages/Connect.jsx#L2

2022-11-01 04:31 UTC, aurelticot commented on package.json
> +    "react-loader-spinner": "^5.3.4",
Was or still used?
If it is still, ok, we keep it.
If it was but no longer is, then we remove it.

2022-11-01 06:20 UTC, cmcWebCode40 commented on package.json
> +    "react-loader-spinner": "^5.3.4",
Yes is still used

2022-11-02 03:37 UTC, aurelticot commented on package.json
> +    "react-loader-spinner": "^5.3.4",
ok

2022-11-02 03:39 UTC, aurelticot approved these changes

2022-11-03 13:09 UTC, merged